DROP TABLE IF EXISTS KINGDOMS;

CREATE TABLE KINGDOMS
(
    kingdom_id VARCHAR(36) PRIMARY KEY,
    gold       INTEGER   NOT NULL,
    citizens   INTEGER   NOT NULL,
    food       INTEGER   NOT NULL,
    dateOfCreation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);